### ISSUE TITLE
gzip= stdin: not in gzip format

### ISSUE THREAD

**Issue by jnbtje** [elsbrock/edgerouter-backup#2]
When running the command we get the following:

admin@er0:~$ curl -sSL https://raw.githubusercontent.com/elsbrock/edgerouter-backup/master/install.sh | sh

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

admin@er0:~$ show version
Version:      v2.0.9-hotfix.4
Build ID:     5521907
Build on:     06/30/22 06:58
Copyright:    2012-2020 Ubiquiti Networks, Inc.
HW model:     EdgeRouter 4

**Comment by elsbrock** [comment]
Thanks for reporting, could you provide the output of `lscpu | grep -i arch | awk '{print $2}'`?

**Comment by jnbtje** [comment]
> Thanks for reporting, could you provide the output of `lscpu | grep -i arch | awk '{print $2}'`?

admin@er0: $ lscpu | grep -i arch | awk '{print $2}'
mips64
admin@er0:~$

**Comment by elsbrock** [comment]
Could you try again? Release job of https://github.com/elsbrock/go-ghwrite did not publish the artifacts.

**Comment by jnbtje** [comment]
Getting there :)

admin@er0: $ curl -sSL https://raw.githubusercontent.com/elsbrock/edgerouter-backup/master/install.sh | sh
go-ghwrite
/config/user-data/config-backup.env: line 2: export: `[': not a valid identifier
/config/user-data/config-backup.env: line 2: export: `!': not a valid identifier
/config/user-data/config-backup.env: line 2: export: `-x': not a valid identifier
/config/user-data/config-backup.env: line 2: export: `': not a valid identifier
/config/user-data/config-backup.env: line 2: export: `]': not a valid identifier
admin@er0:~$

**Comment by elsbrock** [comment]
Can you check if `/config/user-data/config-backup.env` looks OK?

**Comment by jnbtje** [comment]
admin@er0: $ cat /config/user-data/config-backup.env
REPOSLUG=
export GOGHWRITE_TOKEN=if [ ! -x "$GOGHWRITE_BIN" ];
admin@er0:~$ 

It did not request the reposlug and token or should I put this in before somewhere ?

**Comment by elsbrock** [comment]
Mhh, weird, it should have prompted for that. Can you just set it?

**Comment by jnbtje** [comment]
Now it just runs without output and I don't see anything showing up in the repo.

admin@er0: $ cat /config/user-data/config-backup.env
REPOSLUG=jnbtje/edge-mc
GOGHWRITE_TOKEN=xxxxxx
dmin@er0:~$

**Comment by elsbrock** [comment]
You mean when you edit the config? I no longer use Ubiquiti but am surprised it's not working any longer :(

**Comment by jnbtje** [comment]
Yes indeed with the info in previous comment

**Comment by jnbtje** [comment]
Ok getting there token needs to be between ''
Getting 409 Git Repository is empty now

edit:
manually added a file and it is working now

**Comment by elsbrock** [comment]
Great to hear. Thanks for reporting back.
